name-template: 'v$PREVIOUS_TAG'
include-labels:
  - 'changelog'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🐞 Bug Fixes'
    labels:
      - 'bug'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## What’s Changed

  $CHANGES
