name-template: 'Version $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🐞 Bug Fixes'
    labels:
      - 'bug'
exclude-labels:
  - 'skip-changelog'
sort-by: title
sort-direction: ascending
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'next-version-major'
  minor:
    labels:
      - 'next-version-minor'
  patch:
    labels:
      - 'next-version-patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
