name: Lint Code Base

on:
  pull_request:
    branches:
      - develop

jobs:
  run_code_linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v3.11.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSHARP: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
